language: php
php:
  - 5.4
  - 5.5
services:
  - mongodb
before_script:
  - phpenv config-add travis/mongo.ini
  - composer install
  - cp travis/tests/config.php tests/config.php
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
